az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspHvacSensor;1" --twin-id hvacsensor1
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspHvacSensor;1" --twin-id hvacsensor2
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspHvacSensor;1" --twin-id hvacsensor3
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspHvacSensor;1" --twin-id hvacsensor4
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspHvacSensor;1" --twin-id hvacsensor5
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspLightingSensor;1" --twin-id lightingsensor1
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspLightingSensor;1" --twin-id lightingsensor2
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspLightingSensor;1" --twin-id lightingsensor3
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspLightingSensor;1" --twin-id lightingsensor4
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspLightingSensor;1" --twin-id lightingsensor5
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspOccupancySensor;1" --twin-id occupancysensor1
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspOccupancySensor;1" --twin-id occupancysensor2
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspOccupancySensor;1" --twin-id occupancysensor3
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspOccupancySensor;1" --twin-id occupancysensor4
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspOccupancySensor;1" --twin-id occupancysensor5
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspTemperatureSensor;1" --twin-id tempsensor1
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspTemperatureSensor;1" --twin-id tempsensor2
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspTemperatureSensor;1" --twin-id tempsensor3
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspTemperatureSensor;1" --twin-id tempsensor4
az dt twin create -n unrealdemoadter --dtmi "dtmi:digitaltwins:rec_3_3:core:WspTemperatureSensor;1" --twin-id tempsensor5
